#!/usr/bin/env python3
"""
Labor Value Calculator
Developed under the guiding principles of democratic technology ownership and 
the extraction-of-surplus-value critique. This tool calculates the distribution 
of value generated by labor, contrasting capitalist enclosure with cooperative ownership.
"""

import sys

class LaborValueCalculator:
    def __init__(self, hourly_wage: float, hours_worked: float, total_sales: float, 
                 royalties_to_capital: float, royalties_to_labor: float, operating_costs: float):
        """
        Initialize the Labor Value Calculator.
        
        Parameters:
        - hourly_wage: The direct wage paid to the worker per hour.
        - hours_worked: Total hours dedicated to the production process.
        - total_sales: Gross revenue realized from the sales of the product.
        - royalties_to_capital: Intellectual property rents captured by corporate owners/publishers.
        - royalties_to_labor: Direct royalties paid to the creators/workers.
        - operating_costs: Constant capital (C) - infrastructure, servers, tools, raw materials.
        """
        self.hourly_wage = hourly_wage
        self.hours_worked = hours_worked
        self.total_sales = total_sales
        self.royalties_to_capital = royalties_to_capital
        self.royalties_to_labor = royalties_to_labor
        self.operating_costs = operating_costs

    def calculate_metrics(self) -> dict:
        # Gross Revenue (Total realized exchange value)
        gross_revenue = self.total_sales + self.royalties_to_capital + self.royalties_to_labor
        
        # Constant Capital (C) - Material infrastructure costs
        C = self.operating_costs
        
        # Variable Capital (V) - Direct labor compensation
        V = (self.hourly_wage * self.hours_worked) + self.royalties_to_labor
        
        # Net Value Added (N) - The new value created solely by human labor
        # N = V + S = Gross Revenue - Constant Capital
        net_value_added = max(0.0, gross_revenue - C)
        
        # Surplus Value (S) - Value created by labor but captured by capital owners
        # S = Net Value Added - Variable Capital
        S = max(0.0, net_value_added - V)
        
        # Rate of Exploitation (s') - Ratio of unpaid labor to paid labor
        # s' = S / V
        rate_of_exploitation = (S / V) if V > 0 else 0.0
        
        # Labor's Share of Created Value (%)
        labor_share_pct = (V / net_value_added * 100) if net_value_added > 0 else 0.0
        
        # Capital's Enclosure Share (%)
        capital_share_pct = (S / net_value_added * 100) if net_value_added > 0 else 0.0
        
        # Necessary Labor Time (H_n) - Hours spent producing the value of the worker's own wage
        necessary_hours = self.hours_worked * (V / net_value_added) if net_value_added > 0 else 0.0
        
        # Surplus Labor Time (H_s) - Hours spent producing uncompensated value for the employer
        surplus_hours = self.hours_worked * (S / net_value_added) if net_value_added > 0 else 0.0
        
        # Under a worker-owned cooperative, surplus value S is collectively owned.
        # True value of labor per hour = Net Value Added / Hours worked
        true_hourly_value = (net_value_added / self.hours_worked) if self.hours_worked > 0 else 0.0
        
        # Uncompensated hourly value stolen/enclosed
        unpaid_hourly_value = true_hourly_value - (V / self.hours_worked) if self.hours_worked > 0 else 0.0

        return {
            "gross_revenue": gross_revenue,
            "constant_capital": C,
            "variable_capital": V,
            "net_value_added": net_value_added,
            "surplus_value": S,
            "rate_of_exploitation": rate_of_exploitation,
            "labor_share_pct": labor_share_pct,
            "capital_share_pct": capital_share_pct,
            "necessary_hours": necessary_hours,
            "surplus_hours": surplus_hours,
            "true_hourly_value": true_hourly_value,
            "unpaid_hourly_value": unpaid_hourly_value
        }

    def render_report(self):
        m = self.calculate_metrics()
        
        print("=" * 65)
        print("                 LABOR VALUE ANALYSIS REPORT")
        print("=" * 65)
        print(f"Total Hours Contributed:        {self.hours_worked:,.2f} hrs")
        print(f"Direct Compensation (Wages):    ${self.hourly_wage * self.hours_worked:,.2f} (${self.hourly_wage:.2f}/hr)")
        print(f"Labor-Direct Royalties:         ${self.royalties_to_labor:,.2f}")
        print(f"Total Direct Labor Share (V):   ${m['variable_capital']:,.2f}")
        print("-" * 65)
        print(f"Gross Market Sales:             ${self.total_sales:,.2f}")
        print(f"Capital-Enclosed Royalties:     ${self.royalties_to_capital:,.2f}")
        print(f"Constant Capital Cost (C):      ${m['constant_capital']:,.2f}")
        print(f"Net Value Created by Labor (N): ${m['net_value_added']:,.2f}")
        print("=" * 65)
        print("                DISTRIBUTION OF NEWLY CREATED VALUE")
        print("-" * 65)
        print(f"Paid Labor Value (V):           ${m['variable_capital']:,.2f} ({m['labor_share_pct']:.2f}%)")
        print(f"Enclosed Surplus Value (S):     ${m['surplus_value']:,.2f} ({m['capital_share_pct']:.2f}%)")
        print(f"Rate of Labor Exploitation (s'): {m['rate_of_exploitation'] * 100:.2f}%")
        print("-" * 65)
        print("                  TEMPORAL EXPLOITATION BREAKDOWN")
        print("-" * 65)
        print(f"In an average 8-hour shift:")
        shift_ratio = 8.0 / self.hours_worked if self.hours_worked > 0 else 0
        shift_necessary = m['necessary_hours'] * shift_ratio if self.hours_worked > 0 else 0
        shift_surplus = m['surplus_hours'] * shift_ratio if self.hours_worked > 0 else 0
        print(f"  - Necessary Labor (for self):  {shift_necessary:.2f} hours")
        print(f"  - Surplus Labor (for capital): {shift_surplus:.2f} hours")
        print("-" * 65)
        print("                  TRUE VALUE VS. ALIENATED VALUE")
        print("-" * 65)
        print(f"True Value of Labor / Hour:     ${m['true_hourly_value']:,.2f}")
        print(f"Actual Compensation / Hour:     ${m['variable_capital']/self.hours_worked:,.2f}")
        print(f"Enclosed Value / Hour:          ${m['unpaid_hourly_value']:,.2f}")
        print("=" * 65)
        print("                       STRUCTURAL INVERSION")
        print("-" * 65)
        print("Under a Cooperative/Democratic Framework:")
        print("- The $%.2f in surplus value would be collectively owned." % m['surplus_value'])
        print("- There would be zero structural exploitation; labor would receive the")
        print("  full value of its production, democratically voting on operational reserves.")
        print("=" * 65)

if __name__ == "__main__":
    # A standard software project scenario:
    # A software developer is paid $45/hour for 160 hours of work ($7,200 total wages).
    # The firm sells the software for $50,000.
    # The firm pulls in $10,000 in recurring enterprise IP royalties.
    # The developer receives $0 in royalties.
    # Server infrastructure and tools cost the firm $3,000.
    calc = LaborValueCalculator(
        hourly_wage=45.0,
        hours_worked=160.0,
        total_sales=50000.0,
        royalties_to_capital=10000.0,
        royalties_to_labor=0.0,
        operating_costs=3000.0
    )
    calc.render_report()
